server:
  port: 8700

uri:
  api:
    clientes: http://localhost:8080
    cuentas: https://pokeapi.co


spring:
  cloud:
    gateway:
      routes:
        - id: all_clientes
          uri: http://localhost:8080
          predicates:
            - Method=GET
            - Path=/v1/api/cliente/all
          filters:
            - AddRequestHeader=X-GATEWAY-REQUEST-HEADER,GATEWAY-SOLITUD
            - AddResponseHeader=X-GATEYWAY-RESPONSE-HEADER,GATEWAY_RESPONSE
        - id: cliente_id
          uri: http://localhost:8080
          predicates:
            - Method=GET,POST,PUT
            - Path=/promerica/clientes-por-id/{id}
          filters:
            - RewritePath=/promerica/clientes-por-id/, /v1/api/cliente/
            - AddRequestHeader=X-GATEWAY-REQUEST-HEADER,GATEWAY-SOLITUD
            - AddResponseHeader=X-GATEYWAY-RESPONSE-HEADER,GATEWAY_RESPONSE